### ISSUE TITLE
Descriptionが空白の場合

### ISSUE THREAD

**Issue by suinua** [aq17/MineCraftBE-Wiki-Japanese#13]
もしかしたら記入する必要が無いと判断しあえて空白のままにしてるのかも。

例えば[has_damage](https://minecraft.gamepedia.com/Bedrock_Edition_entity_components_documentation#has_damage)なんかはfatalにしか説明の記入が無いしね😒
![image](https://user-images.githubusercontent.com/34801662/57175665-8a37d300-6e89-11e9-90ad-cd0850e7d6af.png)

もし、そうならDescriptionにオプション名の翻訳を載せるのは間違いな気がする

**Comment by suinua** [comment]
括弧でオプション名の翻訳を載せて上げるのがいいのかな～って思ってます😏
![image](https://user-images.githubusercontent.com/34801662/57175765-7a6cbe80-6e8a-11e9-8855-44a6172e3dbc.png)

**Comment by suinua** [comment]
@aq17

**Comment by aq17** [comment]
なるほど、了解です！  
もし最悪付け加える必要があるものは、注釈のマークダウン書いちゃってもいいかも！

**Comment by suinua** [comment]
> もし最悪付け加える必要があるものは、注釈のマークダウン書いちゃってもいいかも！

実はmarkdownに注釈は無いのだ！！
htmlで注釈実装するのもありですが、そうなると人によって書き方が変わってきそうなんですよね。

**Comment by suinua** [comment]
書き方を統一するために翻訳する際のルールをまとめて、ルールについてissueで相談出来たらいいと思います(注釈はいずれ必要になってくるだろうし...)

**Comment by aq17** [comment]
マジか><  
了解です、それは知らなかった...
