### ISSUE TITLE
【要望】翻訳元のURLを載せて欲しいです

### ISSUE THREAD

**Issue by suinua** [aq17/MineCraftBE-Wiki-Japanese#2]
翻訳元のタイトルがID指定してある場合のみになりそうですが、、

`https://minecraft.gamepedia.com/Bedrock_Edition_beta_scripting_documentation#ID`
![image](https://user-images.githubusercontent.com/34801662/57062116-3480f080-6cfa-11e9-9ce5-f69276fefb1c.png)

**Comment by suinua** [comment]
READMEに[元のURL](https://minecraft.gamepedia.com/Bedrock_Edition_beta_scripting_documentation)載せれば十分な気がしますね、、、

**Comment by aq17** [comment]
了解です、次の更新からは載せます。
README.mdと同じ階層か、Scripting APIフォルダの中にテンプレートマークダウンを作ろうかと思っています。
